"""Initial migration

Revision ID: 53a0c2e213ba
Revises: c1687481e013
Create Date: 2025-01-05 22:36:17.479170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53a0c2e213ba"
down_revision: Union[str, None] = "c1687481e013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("password", sa.String(), nullable=False))
    op.add_column("employees", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    op.alter_column("employees", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("employees", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("employees", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint("employees_email_key", "employees", type_="unique")
    op.create_index(op.f("ix_employees_email"), "employees", ["email"], unique=True)
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.create_index(op.f("ix_employees_name"), "employees", ["name"], unique=False)
    op.create_index(op.f("ix_employees_phone"), "employees", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_phone"), table_name="employees")
    op.drop_index(op.f("ix_employees_name"), table_name="employees")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_email"), table_name="employees")
    op.create_unique_constraint("employees_email_key", "employees", ["email"])
    op.alter_column("employees", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("employees", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("employees", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("employees", "is_superuser")
    op.drop_column("employees", "password")
    # ### end Alembic commands ###
