"""Add indexes to customers and vehicles

Revision ID: 6bd37abaa59f
Revises: 
Create Date: 2025-01-04 21:06:27.772765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd37abaa59f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.String(), nullable=False))
    op.create_index('ix_service_history_vin', 'service_history', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_history_vin', table_name='service_history')
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###
